### ISSUE TITLE
Ruby Version 2.5

### ISSUE THREAD

**Issue by nikign** [solidusio/solidus_subscriptions#239]
The current installation requires Ruby version 2.5 according to the following error. Since Ruby@2.5 is deprecated, is there a plan to support more recent versions?
Thanks.
`solidus_subscriptions-1.0.0 requires ruby version ~> 2.5, which is incompatible with the current version, ruby 3.0.1p64`

**Comment by fthobe** [comment]
@jarednorman can be closed I guess
