### ISSUE TITLE
ArgumentError: comparison of String with Gem::Version failed

### ISSUE THREAD

**Issue by styrken** [solidusio/solidus_subscriptions#254]
Check this out:

https://github.com/solidusio-contrib/solidus_subscriptions/blob/a487afef130ebf29679d864d08e83f6d2f8dd140/app/decorators/models/solidus_subscriptions/spree/order/finalize_creates_subscriptions.rb#L12

When booting rails application it fails. It can be fixed by changing the code to

`if Gem::Version.new(::Spree.solidus_version) >= Gem::Version.new('3.2.0.alpha')`

**Comment by styrken** [comment]
https://github.com/solidusio-contrib/solidus_subscriptions/pull/255

**Comment by fthobe** [comment]
@jarednorman solved and merged
