### ISSUE TITLE
Allow guest orders to manage subscriptions via API

### ISSUE THREAD

**Issue by elia** [solidusio/solidus_subscriptions#279]
It should be possible to create and edit subscriptions (e.g. changing intervals(quantity) via API calls.
Currently, though, it seems like an API token is required (which is not available for guest checkouts).

**Comment by kennyadsl** [comment]
Started to look into this ticket, and would like to have more details about this request.

I think that guest users can create and order with a subscribable line item which will end up creating a subscription. Isn't that enough to allow guest users to checkout and create a line item?

**Comment by elia** [comment]
This issue was reported by a 3rd party user, so I don't have the complete details, but looking at the request specs for the solidus_api controllers we're always providing the `Authorization` header with the `spree_api_key`:

https://github.com/solidusio/solidus_subscriptions/tree/master/spec/requests/api/v1

@kennyadsl if the api controllers we have already support guest operations maybe we should just add specs that would both ensure it keeps working and show how to do it.

_Please let me know if there's anything else that I can help clarifying, in case it's needed I can reach out to the users that reported the issue._

**Comment by kennyadsl** [comment]
This is related to the possibility to create and edit subscribable line items (e.g. changing intervals(quantity) via API calls, after it has already been added to the cart.
